# Compilación de proyecto base de C
# Encargado: Estudiante ED
# ----------------------------------

compilar:
	gcc ./incrementos/incrementos.c ./arreglos/arreglos.c script.c -o binario.exe
	./binario.exe

clean:
	rm app.exe
	